# Step: 0

cols = ["AGGRESSIVE_DRIVING","NHTSA_AGG_DRIVING",
        
        "ALCOHOL_RELATED","ILLEGAL_DRUG_RELATED","MC_DRINKING_DRIVER","DRINKING_DRIVER","IMPAIRED_DRIVER",
        
        "AUTOMOBILE_COUNT","BUS_COUNT","SUV_COUNT","VAN_COUNT","SCHOOL_BUS","SMALL_TRUCK_COUNT",
        "PED_COUNT","BICYCLE_COUNT","MOTORCYCLE_COUNT","HEAVY_TRUCK_COUNT","VEHICLE_COUNT",
        
        "COLLISION_TYPE","CROSS_MEDIAN","HIT","SV_RUN_OFF_RD","DEER_RELATED",
        
        "DISTRACTED","FATIGUE_ASLEEP",
        
        "CELL_PHONE","FIRE_IN_VEHICLE","OVERTURNED","SPEEDING","SPEEDING_RELATED",
        
        "UNBELTED_OCC_COUNT","UNBELTED"]

# Step: 1

cols = ["AGGRESSIVE_DRIVING",...........
        
        "MC_DRINKING_DRIVER","DRINKING_DRIVER",..........(mlogit check)
        
        "PED_COUNT","SMALL_VEH_COUNT","MEDIUM_VEH_COUNT","LARGE_VEH_COUNT",
        
        "CROSS_MEDIAN","HIT" (Computer-ji),"SV_RUN_OFF_RD",.......
        
        "DISTRACTED",.........(mlogit check)
        
        "SPEEDING",........
        
        "UNBELTED",........
        
        "COLLISION_TYPE","FIRE_IN_VEHICLE","OVERTURNED",]

In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('dataset/all-crashes-2004-2018.csv', low_memory = False)
data = data[data['MAX_SEVERITY_LEVEL'] < 5]

In [3]:
data['REAR_END_COLLISION'] = [1 if i == 1 else 0 for i in data['COLLISION_TYPE']]
data['HEAD_ON_COLLISION'] = [1 if i == 2 else 0 for i in data['COLLISION_TYPE']]
data['REAR2REAR_COLLISION'] = [1 if i == 3 else 0 for i in data['COLLISION_TYPE']]
data['ANGLE_COLLISION'] = [1 if i == 4 else 0 for i in data['COLLISION_TYPE']]
data['SIDESWEEP_COLLISION'] = [1 if (i == 5 or i == 6) else 0 for i in data['COLLISION_TYPE']]

In [4]:
data['SMALL_VEH_COUNT'] = data["BICYCLE_COUNT"] + data["MOTORCYCLE_COUNT"]
data['MEDIUM_VEH_COUNT'] = data["AUTOMOBILE_COUNT"] + data["SUV_COUNT"]
data['LARGE_VEH_COUNT'] = data["VAN_COUNT"] + data["SMALL_TRUCK_COUNT"] + data["HEAVY_TRUCK_COUNT"] + data["BUS_COUNT"] + data["SCHOOL_BUS"]

In [5]:
cols = ["MAX_SEVERITY_LEVEL",
        "AGGRESSIVE_DRIVING",
        
        "MC_DRINKING_DRIVER","DRINKING_DRIVER",
        
        "PED_COUNT","SMALL_VEH_COUNT","MEDIUM_VEH_COUNT","LARGE_VEH_COUNT",
        
        'HIT_BRIDGE','HIT_DEER','HIT_EMBANKMENT','HIT_FIXED_OBJECT','HIT_GDRAIL','HIT_GDRAIL_END',
        'HIT_POLE','HIT_TREE_SHRUB','HIT_BARRIER',
        
        "CROSS_MEDIAN","SV_RUN_OFF_RD",
        
        "DISTRACTED","SPEEDING","UNBELTED",        
        "FIRE_IN_VEHICLE","OVERTURNED","CELL_PHONE","FATIGUE_ASLEEP",
       
        "REAR_END_COLLISION","HEAD_ON_COLLISION","REAR2REAR_COLLISION","ANGLE_COLLISION","SIDESWEEP_COLLISION"]

In [6]:
data[cols].to_csv('filtered-data.csv', index = None)

In [7]:
data['MAX_SEVERITY_LEVEL'] = data['MAX_SEVERITY_LEVEL'].replace(4,3)
data[cols].to_csv('filtered-data-combined.csv', index = None)

# ----------------------------------------------------------------------------------------------------------------

In [7]:
data['MAX_SEVERITY_LEVEL'].value_counts()

0    92542
3    52512
2     3598
1      983
Name: MAX_SEVERITY_LEVEL, dtype: int64

In [8]:
small = ["PED_COUNT","BICYCLE_COUNT","MOTORCYCLE_COUNT"]
medium = ["AUTOMOBILE_COUNT","SUV_COUNT"]
large = ["VAN_COUNT","SMALL_TRUCK_COUNT","HEAVY_TRUCK_COUNT","BUS_COUNT","SCHOOL_BUS"]

In [9]:
var = 'MEDIUM_VEH_COUNT'

df = data.groupby([var,"MAX_SEVERITY_LEVEL"]).agg({var: 'count'})

df.groupby(level=0).apply(lambda x:100 * x / float(x.sum()))

                                     MEDIUM_VEH_COUNT
MEDIUM_VEH_COUNT MAX_SEVERITY_LEVEL
0                0                          54.399578
                 1                           1.898448
                 2                           5.386470
                 3                          38.315504
1                0                          63.238663
                 1                           0.725137
                 2                           2.689751
                 3                          33.346450
2                0                          62.966601
                 1                           0.320163
                 2                           1.435276
                 3                          35.277960
3                0                          56.912526
                 1                           0.385032
                 2                           1.516063
                 3                          41.186379
4                0                          51.619171
                 1                           0.388601
                 2                           2.266839
                 3                          45.725389
5                0                          49.462366
                 1                           0.358423
                 2                           5.017921
                 3                          45.161290
6                0                          41.176471
                 2                           4.411765
                 3                          54.411765
7                0                          71.428571
                 2                           7.142857
                 3                          21.428571
8                0                          20.000000
                 3                          80.000000
9                0                          33.333333
                 2                          16.666667
                 3                          50.000000
10               0                         100.000000
11               3                         100.000000
12               3                         100.000000

In [9]:
data.groupby(["MC_DRINKING_DRIVER","MAX_SEVERITY_LEVEL"]).count().reset_index()

,MC_DRINKING_DRIVER,MAX_SEVERITY_LEVEL,CRASH_CRN,DISTRICT,CRASH_COUNTY,MUNICIPALITY,POLICE_AGCY,CRASH_YEAR,CRASH_MONTH,DAY_OF_WEEK,...,TOT_INJ_COUNT,SCHOOL_BUS_UNIT,REAR_END_COLLISION,HEAD_ON_COLLISION,REAR2REAR_COLLISION,ANGLE_COLLISION,SIDESWEEP_COLLISION,SMALL_VEH_COUNT,MEDIUM_VEH_COUNT,LARGE_VEH_COUNT
0,0,0,92532,92532,92532,92532,92502,92532,92532,92532,...,13397,13397,92532,92532,92532,92532,92532,92532,92532,92532
1,0,1,934,934,934,934,934,934,934,934,...,120,120,934,934,934,934,934,934,934,934
2,0,2,3483,3483,3483,3483,3476,3483,3483,3483,...,629,629,3483,3483,3483,3483,3483,3483,3483,3483
3,0,3,17087,17087,17087,17087,17063,17087,17087,17087,...,3833,3833,17087,17087,17087,17087,17087,17087,17087,17087
4,0,4,35282,35282,35282,35282,35256,35282,35282,35282,...,2342,2342,35282,35282,35282,35282,35282,35282,35282,35282
5,1,0,10,10,10,10,10,10,10,10,...,2,2,10,10,10,10,10,10,10,10
6,1,1,49,49,49,49,49,49,49,49,...,4,4,49,49,49,49,49,49,49,49
7,1,2,115,115,115,115,115,115,115,115,...,20,20,115,115,115,115,115,115,115,115
8,1,3,105,105,105,105,105,105,105,105,...,7,7,105,105,105,105,105,105,105,105
9,1,4,38,38,38,38,38,38,38,38,...,1,1,38,38,38,38,38,38,38,38

dangerous intersection
weenkend/weeday (or) time of day
cellphone
drunken_drive
licensed

ALCOHOL_RELATED, DRINKING_DRIVER
CELL_PHONE
COLLISION_TYPE
CRASH_MONTH
CURVED_ROAD
DAY_OF_WEEK
DISTRACTED
FATAL
FATIGUE_ASLEEP
HOUR_OF_DAY
ILLEGAL_DRUG_RELATED
INTERSECT_TYPE, INTERSECTION
ROAD_CONDITION
UNLICENSED

In [11]:
data.shape

(149635, 193)